### ISSUE TITLE
Option to disable I2P's Listen Ports

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#143]
In some cases for certain users it may not be possible to forward the ports that I2P listens to. This is okay for I2P since it has mechanisms in place to operate without open ports.

However, it would be nicer if users in these situations could disable the listen ports altogether so that other I2P nodes attempting to communicate with them do not waste time and resources attempting to connect to a node's advertised ports that will never be reached, only to give up.

Something simple like a checkbox that says "Don't open ports" alongside the TCP and UDP listen port setting.

**Comment by zlatinb** [comment]
If you are referring to the TCP and UDP port used for the `I2NP` protocol (the protocol between I2P nodes) then it's not possible to not open those - even if the user cannot forward them, the I2P router uses other I2P nodes to "hole-punch" through firewalls.

It is possible to completely disable the TCP or UDP transports in which case the router will not open these ports at all, but it needs at least one transport in order to communicate with other I2P nodes.  I'm not aware of a way for an I2P router to work if both transports are completely disabled.

**Comment by Searinox** [comment]
If this is true then my concern is unfounded.
