### ISSUE TITLE
How safe is muwire?

### ISSUE THREAD

**Issue by JediMaster25** [zlatinb/muwire#153]
If someone downloads something illegal will I get into trouble for being an exit node or that's only a problem of tor and not i2p? I'm asking after reading [this reddit post about someone raided after using tribler](https://libreddit.esmailelbob.xyz/r/torrents/comments/30jlz0/raided_after_using_tribler/).

**Comment by zlatinb** [comment]
Short answer: no, others cannot access the internet through your MuWire node.

Full answer:

The way MuWire uses I2P does not turn your computer into an "exit node", but it does turn it into a "relay" which provides better anonymity because your node will have more cover traffic.  This is the default method of operation for I2P, all nodes are relays unless they are located in a country where relaying of traffic on behalf of others is illegal.  If you are running MuWire with an embedded router you can go to Status->I2P and look at the "Strict Country" status.  If that is true, means your node is not a relay.

The traffic you relay is encrypted and you have no way of knowing what it is.  The MuWire GUI enforces that you use tunnels which are at least one hop long, which means that your MuWire node hides behind at least one other I2P node and vice versa - the traffic coming out of your node is definitely being routed on behalf of someone else.  It is possible to configure MuWire to use zero-hop tunnels but to do that the user needs to edit configuration files by hand, so the assumption is that they know what risks they are taking.
