### ISSUE TITLE
New, trending, popular files list

### ISSUE THREAD

**Issue by JediMaster25** [zlatinb/muwire#156]
This is probably not possible due to the decentralized nature of the program. I've been doing multiple searches and I haven't managed to find anything, and it gave me the idea that having a few lists would be useful.

**Comment by zlatinb** [comment]
I can't really think of a way to do it that isn't open to spamming because of it being distributed.  I had started a project for something like a torrent site for MuWire hashes called [MuCats](https://github.com/zlatinb/mucats) and it mostly works, as in few people were running MuCats sites.  But I haven't looked at it in a long while.
