### ISSUE TITLE
Freezing a lot & False values of Speed, ETA, Progress bar.

### ISSUE THREAD

**Issue by absolutep** [zlatinb/muwire#170]
![1](https://user-images.githubusercontent.com/97702149/188445978-dbefd99b-be95-4a39-a9c1-90c9c3ce62ae.png)

As you can see from the screenshot - the value of speed is in 100MBps which is not possible in i2p at the moment.

1) Progress bar does not update regularly.

2) ETA does not work at all.

3) Speed bar always remain at 0.

4) This new version hangs a lot.

5) And in the second screenshot you can see - this has started happeinig a lot since I installed the newest version. I do not know what this is. 
![Untitled](https://user-images.githubusercontent.com/97702149/188446885-64524366-93c8-4892-be2f-cc7d4db8a5de.png)

**Comment by zlatinb** [comment]
Hi,

There isn't much I can do about the wrong speed and ETA values for now as they come from the I2P library and that has a lot of bursts.  But  I want to look into more detail into the "Child process exited with code 1" error.  Does that happen immediately after starting MuWire or after it has been running for a while?

**Comment by absolutep** [comment]
I start Muwire and minimize it and do my work. But when I try to open muwire after some time it first freezes and then abruptly closes with this error. I started to face this problem when I installed this new update.

So, isn't there any way - where I can streamline the speed, eta, progress bar - just like it happens in torrent clients?

**Comment by zlatinb** [comment]
Oh, now it makes sense.  When you minimize MuWire it goes into "background mode" and when you maximize it again it is going to be slow for a while until it exits the background mode.  That slowness in turn causes the other error because of reasons specific to the I2P router (clock shift).  I will add an option to not enter background mode in the next beta release which should be in 2-3 weeks.  

Regarding the download speed, look in the `Options` -> `GUI` -> `Smooth download speed over (seconds)`.  The default value is 10 seconds, if you increase that to 60 or something like that it should give you more reasonable speed values.

**Comment by absolutep** [comment]
Ok, so for MuWire to work - Should I not do a minimize?

**Comment by zlatinb** [comment]
Until I add that option try without minimizing if you can.  Let me know if it still behaves poorly.

**Comment by absolutep** [comment]
Ok will do. Thanks.

**Comment by absolutep** [comment]
I converted the GUI settings. Speed, ETA, Progress bar all started working. Thanks.
