### ISSUE TITLE
Autodetect Java 11 or later and install jar files without another java runtime.

### ISSUE THREAD

**Issue by Destroyinator69420** [zlatinb/muwire#175]
Hello Zlatinb,

I am writing concerning the use of jpackage in MuWire. I think that it is inefficient to have one java runtime for each application. Since Java is multitasking, it does not make sense to jpackage when Java 11 is already installed on the system. I have managed to install Oracle JDK 11 on my system and I do not need another Java runtime just to run muwire. This takes up needless resources that do not need to be used. I would like to see an option to run MuWire as a distinct .jar file with a traditional java runtime.

Thanks,
Destoryer2

**Comment by zlatinb** [comment]
Hello,

I use jpackage exactly because it eliminates the need for complex and error-prone java detection logic.  As an added bonus it allows me to control which version of java is going to be used.  I do not consider the extra disk space required for the JRE to be a problem; if you disagree you can use the `.zip` distribution of MuWire which is available [here](https://muwire.com/index-nojs.html) or on the various releases pages here on GitHub.

Zlatinb
