### ISSUE TITLE
Works on Windows?

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#3]
Hello, at the first look i can not find in the REAME on which OS this software works. Also "releases" page do not give me the idea. Screenshot of the app interface and features on the README can be handy.

**Comment by zlatinb** [comment]
Hi, yes it will work on windows as Java programs work on windows, just like I2P does.  You will need to open a command prompt and type "java -jar MuWire-0.1.0.jar".  One non-Windowsy thing is that it will create it's settings directory in %HOME%/.MuWire instead of the Roaming profiles directory.  That's on the todo list to be fixed soon.

Regarding screenshots, I'm waiting for a logo (I'm using the default Griffon one now) and then I'll put some screenshots up.

**Comment by zlatinb** [comment]
Hi, a windows installer that doesn't depend on Java or I2P is now available at https://muwire.com .  There are screenshots there as well.
