### ISSUE TITLE
muwire crash and don't restart

### ISSUE THREAD

**Issue by falcogiallo** [zlatinb/muwire#48]
My configuration: AMD RYZEN 5200G WITH RADEON VEGA GRAPHICS, 8 GB RAM, AMD RADEON RX VEGA 11 GRAPHICS
Client ask for i2p engine: "i2p is disconnected, check and restart muwire"
muwire log:
2020-10-08 20:54:31.641 GRAVE java_util_logging_Logger$log$2 call couldn't initialize core 
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is ' ' with an int value of 0
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 6297

**Comment by zlatinb** [comment]
Hi, can you take a look in your MuWire settings directory for a file called `hosts.json` and delete it.  Your settings directory would be:
`C:\Users\<username>\AppData\Roaming\MuWire` if on windows
`/Users/<username>/Library/Application Support/MuWire` if on mac
`/home/<username>/.MuWire` if on Linux.

Let me know if that helps.

**Comment by falcogiallo** [comment]
I tried as you described but client does not start. The hosts.json file was not recreated on my attempt.
For spaces reasons I have installed muwire on an internal disk, not on the disk where the operating system resides.
I also have over 30,000 files in share, could this be the problem?

[MuWire.log](https://github.com/zlatinb/muwire/files/5354709/MuWire.log)

**Comment by zlatinb** [comment]
Thank you for the log.  Strange because I do not see the original `JsonException` in it and it looks like the client should have started.

Btw you want to sanitize logs, sNL.  Welcome back! :)

Back up all files that end in extension `.json` in the settings directory, then delete them and try again please.

**Comment by falcogiallo** [comment]
These files? C:\Users\User\AppData\Roaming\MuWire\directories

**Comment by falcogiallo** [comment]
Ok muwire has started!  :)

**Comment by zlatinb** [comment]
Great!  Let me know if you have any other questions, if not pls close this issue.

**Comment by falcogiallo** [comment]
Thanks for your help!
muwire booted up and runs smoothly, unfortunately file hashing restarted from the beginning ....
The update to version 0.7.6 was also installed successfully.
I am testing this client to make it known to DDU community, if you are interested in promoting it personally, you can post a comment in P2P section.
Bye!

**Comment by zlatinb** [comment]
Thank you for letting me help :)  Feel free to promote as you wish!

The hashing started over because a file called `files.json` was deleted.  You can try restoring from backup and restarting MuWire.  But it's probably better to just let it re-hash everything, unless that will take days of course.

Take care!
