### ISSUE TITLE
v0.8.2 feedback

### ISSUE THREAD

**Issue by danrobi11** [zlatinb/muwire#51]
Cant set welcome message file. I click on it or I set full path it doesnt work.
Is it normal that muwire uses over 200 threads? 
![muwire threads](https://user-images.githubusercontent.com/48020114/98207060-1278b780-1f09-11eb-8043-473f6bb238de.png)
Also, for like 3 days now muwire connections barely goes over 70

AppImage with embedded router

**Comment by zlatinb** [comment]
I'll take a look at the welcome message problem, I haven't changed anything in that part of the code recently.

Yes, 200 threads is normal, because there are 2 threads per connection.  Also, the newest version has reduced the number of connections to the network to keep background network usage low.

**Comment by zlatinb** [comment]
Chat welcome message file chooser fixed in latest commit.  Give it a try and if it works please close the issue.

**Comment by danrobi11** [comment]
ok Chat welcome message file chooser working now. Whats this new collections section do ?

**Comment by zlatinb** [comment]
It lets you group files together and download them at the same time, like BitTorrent does.  Also if a search matches the description of the collection, all files are returned as results.
