### ISSUE TITLE
Private P2P feature

### ISSUE THREAD

**Issue by cypherbits** [zlatinb/muwire#6]
Could we add a feature allowing for P2P Private sharing? I mean sharing files only with selected "friends" and not in the open. You add friends and you share files only with these friends.
And what about a chat messaging feature?

**Comment by zlatinb** [comment]
In the Options->Configuration->MuWire there is a checkbox "Allow only trusted connections".  If that option is checked then MuWire will allow connections and transfers only to users marked as "Trusted".  However, that will apply to all shared files; if you want to have some files visible only to friends and some visible to everyone then some code changes will be necessary.  I will look into it but it's a pretty serious change so it would take a while.

Chat feature is more difficult and I'm not sure exactly how to do it.

**Comment by ScriptTiger** [comment]
Right now when you go to Options -> Content Control -> and input .* as a regex rule, you can see everyone's public queries. If you limit connections to "allow only trusted connections," does it essentially only send your queries to those you have trusted instead of broadcasting them publicly, so others won't be able to see your queries at all?

**Comment by zlatinb** [comment]
Setting the "allow only trusted connections" will indeed send your queries only to those whom you've marked as trusted, BUT queries get routed one extra hop, so those whom you've marked trusted will in turn broadcast, unless they've selected that option as well.  Even then, they will forward your queries to those whom they have marked trusted, and that may not be the same people you trust.

**Comment by zlatinb** [comment]
It's easy to mark a query as not to be routed an extra hop; however doing so will severely limit the search horizon.  I guess if you're connecting only to trusted peers anyway that isn't so much of a concern.  
If there is interest in such feature I will do it for the next release.

**Comment by ScriptTiger** [comment]
Seeing as how the default behavior is to connect to everyone, someone manually selecting to only connect to trusted individuals is already showing their intent to limit their search horizon. I think the default behavior in turn should be to limit those connections absolutely to only the trusted individuals, but possible also have a checkbox to allow an extra hop so that that intent can also be made clear. I think that's the most natural way to implement it accordingly to user flow.

**Comment by zlatinb** [comment]
Ok, I'll add a "search extra hop" checkbox in the Trust tab in the options panel which is unchecked by default, but is only considered if the "allow only trusted" checkbox is checked as well.  (There is no point in not searching extra hop if you're connecting to everyone).

**Comment by zlatinb** [comment]
Implemented in my latest commit, please test

**Comment by zlatinb** [comment]
@cypherbits 
I'm working on a chat messaging feature which will look a lot like IRC.  I expect to have it finished in a few days, but if you feel like building from source it would help me with testing :)

**Comment by cypherbits** [comment]
Hi, many thanks. I currently very busy, I will try it when I have time.

And many thanks again for your work, seeing just a single developer implementing all of this in this short time is awesome and if you do not get the people feedback you burn out, from my experience... so many thanks.

**Comment by zlatinb** [comment]
Thanks for the kind words.  Chat is done and released in 0.6.3.  Closing this issue :)
