### ISSUE TITLE
[Feature Request] Show Directory names in Searches

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#78]
Now that directory structure and downloads are integrated into MuWire, it would make sense to allow folders to also be found in searches. The benefits to this should be straightforward: suppose an album folder contains files named "track01.mp3", "track02.mp3"... or a comic folder contains "page1.png", "page2.png"... or an application folder contains "setup.exe", "setup.ini", "EULA.txt" ..., the files themselves can be quite non-descript but the folder name would be explicit.

If the person is looking for a specific piece of content - let's say an application called "My Awesome Thingy Installer" and someone is sharing it - these "setup.exe", "readme.txt" files won't show up on search and the user will miss it, but the folder name would show up.

**Comment by zlatinb** [comment]
Yeah it can be done, of course the user will be able to disable searching in folder names in the options, but it will be enabled by default.  Note that this requires adding a flag to the query message that gets sent to the network, so for full benefits of this feature a big part of the network will need to upgrade, but that is not a problem.

A bit more tricky is displaying this to the user - in the "Group by sender" view I can easily add a Tree view for the results from each sender.  But in the "Group by file" view the path to the file will need to be displayed in the lower table, because different senders may have different paths to the same file.

**Comment by Searinox** [comment]
I have set up 2 separate instances and I made sure the listed options are checked including allowing only trusted connections. If I search the name of a folder, I can find results of files from said folders but I am not finding the folders themselves.
