### ISSUE TITLE
[Feature Request] Search Filter for Search Results in Group By File mode

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#80]
I use group by File in my searches and I find that to make it the easiest to spot files. Sometimes I'm forced to search by a more generic term which ends up producing over 200 results. It would be useful in such a case to have a filter just like the one in Browse and Library to narrow down the results by keyword.

**Comment by zlatinb** [comment]
The current filtering logic is pretty simple because it relies on the fact that no new data will arrive while there is an active filter.  With the Library, the filter gets enabled after all shared files load.  With Browse, the filter gets enabled either when all files arrive or when the browse fails.

However with group-by-file we don't know when the last result arrives, so the logic needs to be able to handle updates arriving while a filter is active.  That will make it more complicated, which means I will need more time.

**Comment by zlatinb** [comment]
If I remember correctly the lifetime of a query message is a few minutes, but the real issue is that results from a single responder may take an unknown amount of time to arrive - it depends on the network conditions and the number of results.

**Comment by zlatinb** [comment]
I think I have it working, including with results that arrive after the filter has been applied.  Please test thoroughly  https://muwire.com/downloads/MuWire-0.8.9-GitHub80.zip

**Comment by zlatinb** [comment]
Implemented in 80-2 https://muwire.com/downloads/MuWire-0.8.9-GitHub80-2.zip

also some fixes for preserving row selection during table updates for all tables

**Comment by Searinox** [comment]
Activating filter: multiple selection is now cleared but single selection stays at the position of the item that was selected before activating the filter, even if that item is different.

Clearing filter: both single and multiple selection continue to select the items at the positions from before clearing the filter, even if they are now different items.

**Comment by zlatinb** [comment]
I can't reproduce either one of these.  For me all selections clear on any filtering operation, with or without sorting enabled.

**Comment by Searinox** [comment]
Would be nice if the UI's connectivity config would be separate from that of the I2P backend. Thanks for trying either way.

**Comment by Searinox** [comment]
I think this issue is resolved and you can close it unless you have any other ideas for it. Everything is working well.
