### ISSUE TITLE
[Question] Web of Trust Conflicting Statuses

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#82]
Suppose you have two users in your Contact List Subscriptions. Call them A and B. Now suppose both A and B have the user C on their list. Except A has C marked as Trusted and B has C marked as Distrusted. What happens then?

**Comment by zlatinb** [comment]
You decide what happens.  Trust is never established automatically in order to prevent gaming the system.  You can subscribe to the contact lists of the users you trust, and MuWire will fetch them for you but you need to review them and make an explicit decision whether to trust or distrust user C.

As far as queries are concerned, if "trusted only" mode is enabled, queries will go only one hop unless the "search extra hop" checkbox is checked.  If it is checked the behavior is the same as in regular mode.
